# Generated by Django 5.0.2 on 2024-12-12 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_remove_recipe_author_remove_recipe_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='steps',
        ),
    ]
